### PR TITLE
Fix: #249 - Limit Discharging to battery_current_limit_amps

### LINKED ISSUE #249: Discharge Power Greater Than `battery_current_limit_amps`
**Describe the bug**
It looks like the discharge windows calculation ignores the `battery_current_limit_amps` setting.  Possibly discharges have a negative value and the code is just finding the minimum of either "the perfect" discharge or the setting.  E.g.: if "the perfect" discharge is -100 amps and the `battery_current_limit_amps` is set to 37 => -100 is set/selected.

**To Reproduce**
1. Set you the `battery_current_limit_amps` to something fairly low (in my case, it's set to 37 amps).
2. Run a plan that includes discharging.  It seems if there's a plan that would include somewhat quick cycling to achieve optimum performance that will do it.
3. Look at the plan and see that while your charge power is limited to 37 amps, your discharge can exceed -37.

**Expected behavior**
I would expect that the `battery_current_limit_amps` is respected for both charge and discharge windows.  If it's not symmetrical for all batteries/inverters - perhaps it would make sense to have two settings then?

**Screenshots**
(On the last line you can see the value of `-48 A` even though I've set `battery_current_limit_amps` to 37)
Screenshot 2024-07-01 162217

**Desktop (please complete the following information):**
 - OS: HomeAssistant
 - Browser Chrome
 - Version

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.5.1
 - Browser: Chrome

**Additional context**
One thing that might cause confusion... I've modified my dashboard output (screenshot above) to show charge/discharge in amps rather than W as that's what my inverter requires.  I've used the simple formula of `watts / 48 = amps`.  So perhaps the discharge window is trying to use the `inverter_power_watts` as it's maximum discharge - but I think if `battery_current_limit_amps` is set it should probably be that value as that's the fastest you can charge/discharge a battery.

### PR DESCRIPTION
**Pull request by CraigCallender**
Fixes #249.  The issue was that in the charge window it was correctly using `inverter.charger_power` to calculate max charge, but in the discharge window it was using `inverter.inverter_power`.  The quickest fix would be to just use `inverter.charger_power` in the discharge window calculation (and I've confirmed that this works as expected).  

I thought it might be cleaner though to have the BatteryModel understand the properties of the battery.  And since we're talking about charging/discharging the battery - to switch over to use that.  Therefore I passed along the `battery_current_limit_amps` config into the `BatteryModel` class and calculate the max charge and discharge rates in watts as read-only properties.

I think the only awkward thing here is that we specify the battery limit in amps, but calculate charge/discharge power in watts... so there's a few back and forths.  It does make sense though as most battery specs specify their charge/discharge units in Amps.

Screenshots:
I've set the `battery_current_limit_amps` to 37 and you can see that now it's limited (it does go to 38 in the display, but that's a rounding issue):
image

Whereas the original code produces this:
image

# Question to @fboundy 
I'm assuming 48v batteries in order to convert the `BatteryModel.current_limit_amps` into Watts.  I'm not sure this is a great assumption.  Should I read this from a sensor?  Or create a config value for it?

### CODE REVIEW

**Comment by fboundy** [comment]
Thanks for this. A couple of comments:

- You should be able to use `voltage = self.get_config("battery_voltage", default=50)` as per line 2102 in `pv_opt.py` to get the voltage.
- I use a branch called `patch` for bug fixes like this. This is the branch that I typically have running on my setup. It's currently v3.15.4 but since I've made no updates since the 3.15.3 release it should be consistent with `main`. I pull it into `main` when I'm happy that it's ready for release.
- Similarly `dev` is the branch I use for development so this is the best place for PRs which add new features. It's currently at 3.16.0 and includes a bunch of stuff related to getting IOG. This would be the best place for your cloud integration features.

**Comment by CraigCallender** [comment]
> Thanks for this. A couple of comments:
> 
> * You should be able to use `voltage = self.get_config("battery_voltage", default=50)` as per line 2102 in `pv_opt.py` to get the voltage.
> * I use a branch called `patch` for bug fixes like this. This is the branch that I typically have running on my setup. It's currently v3.15.4 but since I've made no updates since the 3.15.3 release it should be consistent with `main`. I pull it into `main` when I'm happy that it's ready for release.
> * Similarly `dev` is the branch I use for development so this is the best place for PRs which add new features. It's currently at 3.16.0 and includes a bunch of stuff related to getting IOG. This would be the best place for your cloud integration features.

Thanks!  I'll make those changes and target the `patch` branch for this PR.  Give me a few moments.

**Comment by fboundy** [comment]
Just pulled this in and I'm seeing forced charge and discharge which exceeds the power of my inverter:

image

**Comment by CraigCallender** [comment]
Do you have the battery_current_limit_amps set? Or just the inverter.charger_power?

**Comment by fboundy** [comment]
A couple of things I've spotted:

- During discharge it is using `inverter.inverter_power` because this is what limits the forced discharge. `inverter.charger_power` is the capacity of the hybrid inverter to charge the batteries:  for my system this is 3000w vs 3600w for the inverter
- You have switched to just using the `battery_limit_current_amps` but this ignores that fact that this may exceed the capacity of the inverter. I think it needs to be the minimum of the two. In my case above the battery will take/give 100A but that exceeds what the inverter can give/take

**Comment by CraigCallender** [comment]
Makes sense. Let me implement that logic. :)

**Comment by fboundy** [comment]
I've just done it. Working OK now.

**Comment by fboundy** [comment]
PS - appreciate the additional comments, attributes etc. Show's me up for being an amateur!

**Comment by CraigCallender** [comment]
Haha.  I don't think you're an amateur!  I just wanted to make sure my additions were easily reviewed.  I code differently whether it's for my own project or someone elses. :-P

**Pull request merged**
